version: '2'
services:
  origin:
    image: bign8/cdn:origin-latest
    ports:
      - 8080

  # thanks: https://github.com/vegasbrianc/docker-compose-demo
  origin_lb:
    image: dockercloud/haproxy:1.6.3 # https://github.com/docker/dockercloud-haproxy
    ports:
      - 81:80
    links:
      - origin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - origin.bign8.info

  server:
    image: bign8/cdn:server-latest
    environment:
      TARGET: "http://origin.bign8.info"
    ports:
      - 8081
    links:
      - redis

  server_lb:
    image: dockercloud/haproxy:1.6.3
    ports:
      - 82:80
    links:
      - server
    depends_on:
      - origin_lb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - cdn.bign8.info

  client:
    image: bign8/cdn:client-latest
    depends_on:
      - server_lb
      - origin_lb
    environment:
      TARGET: "http://cdn.bign8.info"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
