package main

func genText(id int) []string {
	// TODO: randomize
	return []string{
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc rutrum metus a mi facilisis molestie. Suspendisse placerat erat at tortor vestibulum, et bibendum sapien tincidunt. Aliquam erat volutpat. Integer ut tortor mi. Nam leo libero, rutrum sed tortor vel, pretium ornare nibh. Phasellus nisi mauris, vehicula sit amet venenatis ac, lobortis ac eros. Donec posuere risus vitae gravida porttitor. Proin pretium molestie quam, id volutpat lectus posuere sit amet. Praesent eget varius lacus, a sodales justo. Aliquam sodales, tortor sit amet eleifend bibendum, diam libero pharetra dui, et aliquam elit tellus dapibus lectus. Suspendisse a leo lorem.",
		"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin viverra mauris eu vehicula elementum. Sed consequat eros non faucibus hendrerit. Etiam cursus velit a leo auctor, in tristique est venenatis. Nulla rhoncus, nunc sed pulvinar interdum, tortor turpis malesuada ligula, quis dapibus eros felis nec dui. Sed vel est consectetur, commodo ipsum vitae, imperdiet risus. Vestibulum gravida bibendum elit sed varius. In molestie neque sit amet pellentesque dapibus. Donec ac libero volutpat, aliquet justo ac, aliquam libero. Nullam ut feugiat metus, vel facilisis purus. Fusce dignissim sem ut odio vehicula ullamcorper. Praesent dignissim porta laoreet. Aenean molestie commodo est a semper. Nunc varius eu tellus eget ultrices.",
		"Aenean ac urna at est viverra dictum. Vestibulum id ornare tortor. Vestibulum elit nisl, consequat quis feugiat nec, auctor ut leo. Donec fermentum scelerisque nunc ut malesuada. Phasellus at condimentum nisl. Sed imperdiet arcu at blandit facilisis. Morbi tristique ligula felis, quis convallis lacus interdum in. Donec vitae rutrum orci. Nullam pulvinar massa ut felis condimentum tincidunt. Nullam efficitur imperdiet magna pharetra pellentesque.",
		"Ut sed libero est. Nunc egestas odio ac elementum viverra. Maecenas eu maximus neque, a convallis tortor. Ut at vestibulum ipsum. Cras dui dolor, mollis ac lobortis tincidunt, tincidunt at sem. Curabitur odio ipsum, dictum ac pellentesque a, ultrices quis elit. Donec accumsan sed dui et eleifend. Nam molestie rutrum sem a pulvinar. Pellentesque tempus, metus in sagittis placerat, mi nulla sodales diam, nec consequat tellus nunc eget enim. In ac eros quis lacus imperdiet posuere. Curabitur dapibus ac erat non vulputate. Etiam ornare nunc augue, vel semper nunc feugiat non.",
		"Duis aliquet, diam vitae euismod sodales, magna augue feugiat urna, at viverra risus neque et purus. Vestibulum dapibus leo non malesuada sollicitudin. Sed egestas libero sed quam rutrum porta. Nam tempus aliquam interdum. Pellentesque mauris justo, faucibus nec orci id, tempor mollis elit. Sed ut metus vel massa accumsan efficitur. Sed non erat enim. Mauris commodo mauris a neque convallis, eget interdum nisi viverra. Pellentesque aliquet, augue nec pharetra feugiat, est lectus venenatis mi, blandit mattis risus ante eu orci.",
		"Ut dignissim fringilla lorem, quis ornare velit. Ut sollicitudin augue non sagittis ultrices. Etiam rutrum porttitor odio, vel scelerisque lorem facilisis et. Vivamus dolor magna, laoreet vel porttitor ac, finibus eleifend nisi. Donec diam nisl, condimentum ut maximus id, gravida sit amet metus. Phasellus porttitor purus eget vestibulum iaculis. Sed mattis laoreet ultricies. Morbi eu malesuada orci. Sed consectetur quis nisi non varius. Pellentesque accumsan maximus libero et accumsan. Maecenas vitae commodo massa. Mauris nec aliquet massa. Maecenas vitae venenatis elit, sit amet suscipit arcu. In hac habitasse platea dictumst. Nam rutrum diam at luctus ornare.",
		"In tempor ut quam sit amet malesuada. Quisque tempor congue leo molestie imperdiet. Suspendisse mattis urna eget metus posuere bibendum. Cras vitae metus erat. Etiam magna nunc, sollicitudin vitae dui in, maximus ultrices leo. Vestibulum posuere lacus lacus, ut malesuada ipsum molestie et. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum sollicitudin laoreet elementum. Proin in dolor dapibus, malesuada turpis et, convallis quam. Nullam at cursus purus. Praesent at dolor in est ornare aliquet nec ut ex. Praesent eget tristique orci. Sed varius vehicula diam vel rutrum.",
		"Sed iaculis sapien nec orci vestibulum gravida. Etiam semper leo id fringilla maximus. Nullam ligula erat, tempor vitae elit nec, dignissim venenatis nisi. Aliquam erat volutpat. Vivamus erat quam, malesuada non faucibus eget, egestas id risus. Nam eu pulvinar magna, ac imperdiet mauris. Nam odio nisl, sagittis vel rhoncus porta, sagittis in urna. Pellentesque scelerisque ipsum nec massa facilisis consectetur. Vestibulum maximus turpis sed ultricies mattis.",
		"Aliquam id maximus magna. Curabitur ultricies leo orci, vitae tristique enim bibendum a. Praesent varius sollicitudin ornare. Curabitur eleifend nibh vel viverra auctor. Morbi in tempor turpis, eget laoreet augue. Curabitur metus nunc, fringilla eget nulla convallis, ultricies commodo nisi. Mauris fringilla dignissim mollis. Nunc vel lectus sed nibh ornare ultricies at ut mauris. Quisque suscipit urna congue feugiat feugiat. Etiam ut laoreet diam.",
		"Fusce id odio a mi posuere porttitor. Sed sollicitudin, enim id interdum sagittis, eros nulla commodo diam, id fringilla diam diam eget metus. Nam eleifend bibendum nisi, eu aliquam mauris luctus eget. Etiam dapibus erat eget erat pharetra condimentum. Etiam ullamcorper venenatis facilisis. Etiam interdum enim sed mi sollicitudin, sed tristique tortor facilisis. In at sodales urna. Nunc nec sagittis ligula. Vestibulum vitae sapien justo. Aenean eu mi sed neque lobortis accumsan. Integer vehicula tempor arcu, sit amet lacinia justo iaculis nec. Morbi eget dui in justo hendrerit luctus. Aenean non magna a enim dictum varius eu eget quam. Ut ultrices orci velit, at pulvinar lorem posuere vel. Morbi a neque id mi accumsan varius ac at leo. In hac habitasse platea dictumst.",
		"Curabitur fringilla pulvinar enim sed consequat. Quisque venenatis euismod sodales. Pellentesque interdum lectus magna, vitae suscipit ante sollicitudin sed. Ut fermentum arcu ac urna porta, ullamcorper interdum metus iaculis. Duis eu faucibus ipsum, nec lacinia lorem. Integer pellentesque in erat quis consectetur. Phasellus vitae ex nec lorem vulputate semper. Proin ac iaculis turpis. Nam hendrerit tortor et nunc rutrum viverra.",
		"Praesent at quam id augue scelerisque vulputate quis sit amet diam. Nulla vitae est et augue porta faucibus. Etiam quis neque nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam malesuada lacinia eros et tristique. Phasellus euismod sodales ligula vitae vestibulum. Ut scelerisque magna ultricies ante aliquet aliquet. Proin ligula lacus, convallis eget quam ac, ornare consequat ex. Vivamus gravida varius elit, ut vehicula libero commodo a. Morbi id dolor a enim malesuada porttitor.",
		"Morbi consectetur risus in vulputate scelerisque. Nunc maximus augue odio, sit amet rhoncus massa tristique ut. Pellentesque lectus sapien, ultricies nec ullamcorper sed, ullamcorper vitae dui. Aenean luctus felis nec quam venenatis cursus. Vestibulum ex ex, fermentum dapibus condimentum non, pharetra a purus. Sed et dignissim enim, id feugiat nulla. Sed sed finibus est. Nulla in mattis nibh. Donec nec tristique purus, eget scelerisque libero. Proin a imperdiet dui. Nam pulvinar ante id justo vulputate commodo. Pellentesque ut mauris volutpat, ultrices nisi vel, ornare orci. In dapibus lacus laoreet aliquet vestibulum. Nulla mi dolor, congue id urna sit amet, ullamcorper interdum leo. Maecenas fringilla volutpat ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
		"Cras eget dapibus velit. Nam id augue in nunc lobortis congue. In sed iaculis sem, a laoreet nibh. Nullam scelerisque nunc eget convallis ultrices. Nunc condimentum felis diam, at efficitur enim ultrices vitae. Nullam molestie dolor augue, vitae placerat tortor sollicitudin fringilla. Nam in nunc sit amet leo condimentum pharetra. Integer auctor orci in risus auctor ultricies.",
		"Curabitur est odio, pellentesque vitae fermentum nec, porttitor interdum ex. Curabitur id imperdiet ligula, sed congue augue. Nulla at nisl aliquet, semper ex sed, congue ipsum. Phasellus pellentesque sagittis nisi, quis ullamcorper odio faucibus sed. Cras vulputate rhoncus lorem, at consequat lorem mollis et. Pellentesque mauris dui, dapibus quis velit malesuada, pellentesque vestibulum augue. Cras id dictum orci. Aenean tempus diam non arcu iaculis, ut tempor urna tincidunt. Nullam rhoncus vehicula erat. Nunc rhoncus mi quam, eget iaculis nunc dictum ut. Praesent ac justo nec augue iaculis sollicitudin at sed mauris.",
		"Etiam maximus nec quam nec varius. Etiam erat tellus, feugiat et pellentesque et, varius et eros. Vivamus imperdiet tortor sit amet lectus dignissim pharetra. Integer id justo a massa ultrices tempus nec in mauris. Vestibulum vitae turpis quam. Duis vel elementum nunc, eget sollicitudin metus. Aliquam vitae sagittis nulla. Mauris ullamcorper libero non massa molestie, et placerat nulla fringilla. Nam sit amet magna et elit tempor laoreet et id velit. Praesent volutpat venenatis nisl, eu maximus augue tristique in. Praesent scelerisque augue ac velit condimentum, eu pretium leo consectetur. Pellentesque sit amet malesuada augue, eu dictum massa.",
		"Curabitur sollicitudin ligula metus, eget sagittis enim aliquet et. Nam sit amet varius lacus. Donec ultrices, tortor eu imperdiet tincidunt, neque nulla dictum metus, id facilisis nisl orci a ante. Proin efficitur arcu eget felis ullamcorper, et mattis odio accumsan. Sed condimentum urna ut vestibulum luctus. Praesent malesuada sagittis erat, ac imperdiet arcu feugiat et. Proin dignissim commodo sapien, non efficitur odio. In sit amet porttitor enim, in pharetra libero. Duis fringilla accumsan convallis. Aliquam tincidunt nulla viverra quam pulvinar dignissim. Maecenas a convallis quam, ac volutpat quam. Ut non est vitae orci ultrices dapibus. Praesent facilisis diam vitae nibh egestas, sit amet fringilla urna malesuada.",
		"Aliquam non scelerisque felis. Vivamus eu ornare magna. Integer urna nisl, bibendum malesuada ante sit amet, blandit convallis est. Suspendisse ut ipsum nulla. Suspendisse a fermentum massa, et ullamcorper nibh. Vivamus non efficitur erat. Aliquam vel iaculis neque, eget iaculis lacus. Mauris rutrum neque sit amet velit varius bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis sed porttitor mauris. Suspendisse at congue est, at faucibus massa.",
		"Maecenas pharetra quis orci a efficitur. Maecenas tortor quam, suscipit nec condimentum et, imperdiet non leo. Vivamus a varius mauris. Donec volutpat massa purus, vel euismod leo consectetur at. Cras a lacus id nibh malesuada varius. Suspendisse elementum efficitur nulla, non vestibulum purus rhoncus sit amet. In vel est ex. Pellentesque ut sem augue.",
		"Nulla facilisi. Morbi dapibus vitae orci vel luctus. Curabitur pellentesque vel nisi at efficitur. Proin sed ex egestas, dignissim magna blandit, iaculis turpis. Fusce facilisis justo non aliquam finibus. Morbi facilisis malesuada metus. Fusce sed imperdiet orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse euismod est velit, in tempus risus pulvinar ac.",
		"Aliquam tristique eros quis ex faucibus, et hendrerit mauris imperdiet. Nulla ornare ligula at laoreet pulvinar. Nunc felis orci, sodales et ligula ut, varius tincidunt arcu. Curabitur ut quam tincidunt, accumsan ex at, eleifend ligula. Nulla accumsan odio at tortor tristique mollis. Mauris molestie non tellus eu accumsan. Donec leo sem, tristique et venenatis eu, aliquam vitae ipsum. Nam in maximus erat, nec facilisis diam. Proin lacinia tellus at odio euismod, vitae aliquam risus tincidunt.",
		"Integer vel odio quam. In laoreet rutrum risus eget tincidunt. Phasellus venenatis quam a ornare mollis. Maecenas molestie et neque ut mollis. Curabitur ut leo eget eros finibus placerat sit amet vitae libero. Curabitur ornare eleifend ultricies. Aliquam quis neque et ipsum pulvinar dignissim. Ut egestas tempus erat, eget lobortis turpis finibus at. Integer vehicula erat eu metus efficitur, nec condimentum lectus pretium. Aenean vehicula dictum fermentum. Mauris quis libero sed eros commodo suscipit.",
		"Suspendisse rhoncus convallis enim vel hendrerit. Maecenas suscipit aliquet massa ac dapibus. Fusce nec imperdiet nibh. Integer suscipit, diam vitae vestibulum auctor, mi orci accumsan purus, vel euismod nunc nibh et turpis. Sed a nisl elementum, maximus augue a, semper dolor. Suspendisse id lacus justo. Nullam viverra, nisl vitae ultricies facilisis, magna orci luctus nisl, vel interdum nisi enim vitae urna. Vivamus facilisis dapibus imperdiet. Nam elit eros, consequat quis velit a, volutpat efficitur neque. Mauris sed ante et leo ornare blandit a ac purus. Aliquam molestie arcu eu arcu pharetra hendrerit. Donec luctus pretium venenatis.",
		"In tristique felis nulla, vitae efficitur magna fringilla ut. Quisque cursus, est ut efficitur ultricies, nunc neque malesuada orci, interdum laoreet orci neque sed enim. Proin consequat eros in lorem euismod viverra. Nam imperdiet condimentum erat, eget euismod erat semper sed. Donec sodales libero vitae convallis fringilla. Proin pharetra sollicitudin viverra. Sed scelerisque ex sem, at vehicula lacus cursus sit amet. Etiam congue varius tortor, vitae aliquet nulla dignissim et. Nulla non justo purus. Quisque interdum nisi efficitur eleifend egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus, urna ac mattis imperdiet, odio quam sollicitudin turpis, eget auctor dui est vitae ex.",
		"Sed ac dui ultricies, ullamcorper nulla nec, elementum metus. Suspendisse venenatis feugiat ligula, quis dapibus quam commodo et. Mauris non erat a neque suscipit elementum. Fusce in consequat ligula. Donec pretium enim magna, eu viverra urna aliquam vitae. Morbi nec nisl bibendum, vestibulum ligula sit amet, ultrices turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis elementum auctor lobortis. Aliquam erat volutpat.",
	}
}
